Extended readme.md
I2SE/in-tech-sc-bsp pull request #4
Opened 2023-05-24 12:47 UTC by orangeDK

Added a new chapter about flashing an image for Charge Control C and Charge Control M products.

2023-05-24 12:52 UTC, barsnick commented on README.md
> +3.5 [Flashing an image](#flash)
"Image" (capital) in 3.4, vs. "image" (non-capital) in 3.5.

2023-05-25 11:49 UTC, mhei requested changes

2023-05-25 11:49 UTC, mhei commented on README.md
> +The resulting image will be found in `yocto/build/tmp/deploy/image/<machine>` have a filename similar to `core-image-minimal-platform-1234567890-rootfs.ext4.gz`
I suggest: ... will be found in ..., (comma here before) having a filename...

2023-05-25 11:49 UTC, mhei commented on README.md
> +### Flashing an image <a name="flash"></a>
here too: uppercase I in image

2023-05-25 11:49 UTC, mhei commented on README.md
> +The internal storage of the products Charge Control C and M is divided into several partitions and uses rauc to handle updates. If you are interested in adding rauc to your own image you can take a l
please use always uppercase "RAUC" since it is an abbreviation

2023-05-25 11:49 UTC, mhei commented on README.md
> +| **`Partition`** | **`Size`**  | Description |
formatting nitpicks: partition and size is both, marked as bold and code; description neither nor, I'd suggest to drop both

2023-05-25 11:49 UTC, mhei commented on README.md
> +| **`Partition`** | **`Size`**  | Description |
same as above

2023-05-25 11:49 UTC, mhei commented on README.md
> +1. To Identify the currently booted partition execute the following command and look for the partition which is marked as `good`. For this example we will be on partition `/dev/mmcblk0p1` on a Charge
small i in identify

2023-05-25 11:49 UTC, mhei commented on README.md
> +umount /dev/mmcblk0p2 -l
I'd not recommend to use option -l here, the umount should work without - if not, then something is wrong

2023-05-26 07:16 UTC, mooraby commented on README.md
> +The internal storage of the products Charge Control C and M is divided into several partitions and uses rauc to handle updates. If you are interested in adding rauc to your own image you can take a l
Would prefer to have RAUC in capital letters.
Also "RAUC's documentation"

2023-05-26 07:16 UTC, mooraby commented on README.md
> +mount /dev/mmcblk0p2 /mnt
not sure if we need sudo for mount and umount on the target platform

2023-05-26 07:16 UTC, mooraby commented on README.md
> +rauc status
It would be better if an example of `rauc status` output is added

2023-05-26 09:56 UTC, orangeDK commented on README.md
> +mount /dev/mmcblk0p2 /mnt
Not necessary.

2023-05-26 10:02 UTC, mooraby approved these changes

2023-05-26 11:50 UTC, merged