Improve README
I2SE/in-tech-sc-bsp pull request #5
Opened 2023-10-13 07:51 UTC by lategoodbye

Currently the README.md assumed that the reader has also read the AN12 including the product to platform mapping. In order to keep the burden low, replace the product with platform names. This should avoid confusion for new users.

Btw update servicedesk link and drop stray character.

2023-10-17 15:16 UTC, mhei requested changes
The update of the service desk link and the stray character is ok. But I cannot find the product "Tarragon" on the chargebyte's homepage. And in case of EVAcharge SE, it is even worse: this BSP is for Charge Control M only since the partitioning is different from the BSP-only product "EVAcharge SE". So I recommend to stay with the current wording.

2023-10-17 15:20 UTC, lategoodbye commented
After creating this pull request i noticed the kirkstone-everest branch. I will try to use that for orientation.

2023-10-18 14:33 UTC, lategoodbye commented
I force pushed the commit.

2023-10-18 15:20 UTC, mhei approved these changes
Thanks, LGTM now.

2024-01-08 14:53 UTC, merged